### ISSUE TITLE
Duplicate Profiles from every Ministry Safe job Occurence

### ISSUE THREAD

**Issue by bkerekffy** [BEMADEV/Ministry-Safe#4]
Hi Bema Developers,
I am using you plugin in our church's (Athey Creek Christian Fellowship's) Rock instance. We have noticed a weekly addition of duplicate profiles for staff and other 'high access' members in the system. These duplicates always have the Ministry Safe plugin logged under them as a recent interaction from when they were created. I tried manually running the Ministry Safe job, and it did indeed recreate all duplicates that the merge team previously merged. A theory when talking with a partner at Triumph is that this would be due to staff members and other 'high access' volunteers being marked as a 'high level' security. This maybe would trigger the workflow to create duplicates instead of attach the results to their current profile. I was wondering if there is a fix that could be provided for this to prevent from having to re-merge all staff and high access volunteer profiles on a weekly basis?
God Bless!
- Brayton Kerekffy

Here a screen shot of the interactions shown on a duplicated staff or high-level user
<img width="432" alt="thumbnail" src="https://github.com/BEMADEV/Ministry-Safe/assets/148915082/c338c881-5d5e-4c63-a707-5e37a345bef2">

### Expected Behavior

Ministry safe job is run on existing profiles, no duplicates are a result of this job.

### Actual Behavior

Ministry safe job creates duplicates.

### Steps to Reproduce

- Set members to a high level access
- Take ministry safe test for these high level access members
- Run job to attach scores

### Rock Version

Rock McKinley 15.1

### Plugin Version

1.12.4.14

### Client Culture Setting

en-US

**Comment by tcavaletto** [comment]
Hi @bkerekffy . If there's already an External Id set on the Ministry Safe profile in the format _paPersonAliasId_ ( see example below), then the plugin will skip the Find or Create a Person step and just use that. To prevent us circumventing the new Rock security features, I recommend instead you update the Ministry Safe profiles of your high security people with these external ids.
![image](https://github.com/BEMADEV/Ministry-Safe/assets/5482014/ac7ffbb9-df46-41d3-8a3d-d8614c97bc86)

**Comment by bkerekffy** [comment]
Thank you for your help! My team and I will take a look at this.
